# Generated by Django 2.1.2 on 2018-10-29 00:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(default=datetime.datetime(2018, 10, 29, 0, 42, 43, 874676, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
